### PR TITLE
Added ability to follow anchors to heading-id

### PR DESCRIPTION
**Pull request by sonjiku**
Pretty easy fix thanks to how well you've written your code. I suggest adding some more comments to make it easier for people to contribute, though the documentation was an enormous help!

Makes the wiki link handler look for exact, case-sensitive header-id match for anchors. Tested and works great!

### CODE REVIEW

**Comment by lervag** [comment]
> Pretty easy fix thanks to how well you've written your code.

Thanks!

> I suggest adding some more comments to make it easier for people to contribute, though the documentation was an enormous help!

It's hard to say which parts would benefit from more comments. I don't mind adding comments, but I usually don't comment things unless I realize it may be useful. But I'll take note and use more comments in the future.

> Makes the wiki link handler look for exact, case-sensitive header-id match for anchors. Tested and works great!

Could you give me a few examples and/or write a test for this as well?

**Comment by lervag** [comment]
Related tests are under `tests/test-links`, e.g. here: https://github.com/sonjiku/wiki.vim/blob/master/test/test-links/test-follow-anchored.vim.

The tests may be slightly harder to understand. If you give me a few examples I could write the test myself.

**Comment by sonjiku** [comment]
Tests made and feature works as expected.

**Comment by lervag** [comment]
Thanks! On my end, two of the tests fail:

```
lervag@lotti: wiki.vim/test on  heading-id
❯ make
**** SYSTEM INFORMATION ****
commit e2863bc9aaa152beb357ca94f14a434d0f08e23f (HEAD -> heading-id)
Author: sonjiku <dev.50nj1ku@erine.email>
Date:   2024-09-13 04:57:52 +0300

    Fixed. Should pass all the tests I've made.
NVIM v0.11.0-dev-727+g5ddf2ab768
Build type: Release
LuaJIT 2.1.1723675123
Run "nvim -V1 -v" for more info
**** SYSTEM INFORMATION ****
make -C test-complete
make -C test-graph
make -C test-init
make -C test-journal
make -C test-links
test-follow-anchored-id.vim:18
  Expected: 16
  Observed: 9
test-follow-anchored-id.vim:22
  Expected: 22
  Observed: 10
make[1]: *** [Makefile:11: test-follow-anchored-id.vim] Error 1
make: *** [Makefile:12: test-links] Error 2
```

These correspond to lines 9 and 10 in the new `index.md`. I'm not quite sure why they fail, and I don't have time to look into it further until possibly tomorrow.

**Comment by sonjiku** [comment]
Lol, I hadn't slept while hacking it together, but now all tests pass.

**Comment by lervag** [comment]
Thanks!

**Pull request merged**
