### PR TITLE
Add option for function to transform paths of new pages

### PR DESCRIPTION
**Pull request by wbthomason**
Per discussion in #64, this PR adds a very simple implementation of an option to specify a function which will be invoked to transform the paths of pages created through `WikiOpen`.

One design point that may need more iteration is that this runs the function for **all** invocations of `WikiOpen` - it does not test that the page is being created (rather than opened) first, and leaves this to the user (as shown in the example added to the docs). This may be good enough, or it may be better to add logic to ensure that the transformation function is only run for new pages.

### CODE REVIEW

**Comment by lervag** [comment]
Thanks, this looks good. I'll merge immediately, but I have one question: Would it be better if these options instead were named `g:wiki_map_link_target` and `g:wiki_map_create_page`? I'm thinking that it could make it more clear that these options are related with regard to their function, and as such, improve discoveribility?

**Comment by wbthomason** [comment]
Yeah, that seems like a good idea. I'll push a commit with the renaming.

**Comment by lervag** [comment]
You were fast, and I was already in the process of merging and making some minor modifications, so I made the change of option names myself.

Thanks, I appreciate your effort! It is very nice to get some extra hands on deck, as I've abit too much on my plate lately.

**Comment by wbthomason** [comment]
Happy to help! Thanks!

**Pull request closed without merging**
